// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.springframework.roo.northwind.model;

import org.springframework.roo.northwind.model.CityTest;
import org.springframework.roo.northwind.model.dod.CityFactory;
import org.springframework.roo.northwind.model.dod.CustomerOrderFactory;
import org.springframework.roo.northwind.model.dod.PartyFactory;
import org.springframework.roo.northwind.model.dod.StoreFactory;
import org.springframework.roo.northwind.model.dod.SupplierFactory;

privileged aspect CityTest_Roo_JpaUnitTest {
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private CityFactory CityTest.cityFactory = new CityFactory();
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private CustomerOrderFactory CityTest.customerOrderFactory = new CustomerOrderFactory();
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private PartyFactory CityTest.partyFactory = new PartyFactory();
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private StoreFactory CityTest.storeFactory = new StoreFactory();
    
    /**
     * TODO Auto-generated attribute documentation
     * 
     */
    private SupplierFactory CityTest.supplierFactory = new SupplierFactory();
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CityFactory
     */
    public CityFactory CityTest.getCityFactory() {
        return cityFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param cityFactory
     */
    public void CityTest.setCityFactory(CityFactory cityFactory) {
        this.cityFactory = cityFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return CustomerOrderFactory
     */
    public CustomerOrderFactory CityTest.getCustomerOrderFactory() {
        return customerOrderFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param customerOrderFactory
     */
    public void CityTest.setCustomerOrderFactory(CustomerOrderFactory customerOrderFactory) {
        this.customerOrderFactory = customerOrderFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return PartyFactory
     */
    public PartyFactory CityTest.getPartyFactory() {
        return partyFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param partyFactory
     */
    public void CityTest.setPartyFactory(PartyFactory partyFactory) {
        this.partyFactory = partyFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return StoreFactory
     */
    public StoreFactory CityTest.getStoreFactory() {
        return storeFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param storeFactory
     */
    public void CityTest.setStoreFactory(StoreFactory storeFactory) {
        this.storeFactory = storeFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @return SupplierFactory
     */
    public SupplierFactory CityTest.getSupplierFactory() {
        return supplierFactory;
    }
    
    /**
     * TODO Auto-generated method documentation
     * 
     * @param supplierFactory
     */
    public void CityTest.setSupplierFactory(SupplierFactory supplierFactory) {
        this.supplierFactory = supplierFactory;
    }
    
}
